version: '3'

services:
  backend:
    build: ./services/backend
    ports:
      - 5000:5000
      - 5678:5678
    environment:
      DATABASE_URL: postgres://bachelor:bachelor@db:5432/bachelor_db
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    volumes:
      - ./services/backend:/app
    command: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m uvicorn src.main:app --host 0.0.0.0 --port 5000 --reload
    depends_on:
      - db

  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080

  db:
    image: postgres:15.1
    environment:
      POSTGRES_USER: bachelor
      POSTGRES_PASSWORD: bachelor
      POSTGRES_DB: bachelor_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
    depends_on:
      - zookeeper


volumes:
  postgres_data:
