name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        working-directory: services/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: services/backend
        run: pytest tests

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: services/frontend
        run: npm ci

      - name: Run tests
        working-directory: services/frontend
        run: npm test

      - name: Build
        working-directory: services/frontend
        run: npm run build

  deploy:
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Add any steps required to deploy your application
      # For example, you can use GitHub Pages, AWS, Google Cloud, or Heroku
